/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Details */

#ifndef _Included_Details
#define _Included_Details
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Details
 * Method:    returndays
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_Details_returndays
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Details
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Details_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Details
 * Method:    modifyACL
 * Signature: (Ljava/lang/String;Ljava/lang/String;CI)V
 */
JNIEXPORT void JNICALL Java_Details_modifyACL
  (JNIEnv *, jobject, jstring, jstring, jchar, jint);

#ifdef __cplusplus
}
#endif
#endif
